[build]
  # We are moving the install command to the very front to ensure it runs
  # The environment variable set in the dashboard will now apply to this
  command = "npm install $NPM_FLAGS && npx prisma generate && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"