[build]
  # We chain the install with the flag, then generate prisma, then build
  command = "npm install --legacy-peer-deps && npx prisma generate && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"